### ISSUE TITLE
P0 Submission for Codepath Review

### ISSUE THREAD

**Issue by huhx0015** [huhx0015/CAB0_SimpleTodo#1]
Hello, /cc @codepathreview @codepath

Just informing you that my P0 solution has been completed and is ready for review. Please let me know if anything else is needed. Thanks!

**Comment by nesquena** [comment]
Hi Michael,

Thanks for applying and submitting your pre-work. Based on your LinkedIn, your background indicates you have a significant amount of existing Android development experience. We appreciate you applying to participate, however our Android bootcamp is optimized for senior engineers without significant existing experience in Android.

Furthermore, since we have a limited number of free seats, we like to optimize our impact by selecting people that have the most to benefit from participating. To be clear, those with significant Android experience can still benefit from the program but not as significantly as those that don't.

Let me know if I have misunderstood your existing Android experience and thanks for your understanding. Alternatively, we do offer sponsored seats for companies that want to send their Android developers through this training (used by many top startups such as Dropbox and Hipmunk), happy to tell you more about that if interested.
